### ISSUE TITLE
Issue..

### ISSUE THREAD

**Issue by Maninandha** [antonydeepak/ResumeParser#18]
java.io.FileNotFoundException: D:\ANNIEResumeParser.gapp (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1038)
	at gate.util.persistence.PersistenceManager.isXmlApplicationFile(PersistenceManager.java:1013)
	at gate.util.persistence.PersistenceManager.loadObjectFromUrl(PersistenceManager.java:857)
	at gate.util.persistence.PersistenceManager.loadObjectFromFile(PersistenceManager.java:831)
	at ResumeParser.ResumeTransducer.src.code4goal.antony.resumeparser.Annie.initAnnie(Annie.java:40)
	at ResumeParser.ResumeTransducer.src.code4goal.antony.resumeparser.ResumeParserProgram.loadGateAndAnnie(ResumeParserProgram.java:95)
	at ResumeParser.ResumeTransducer.src.code4goal.antony.resumeparser.ResumeParserProgram.main(ResumeParserProgram.java:274)

**Comment by Maninandha** [comment]
fixed myself
