### ISSUE TITLE
gate.util.GateException: couldn't open creole.xml

### ISSUE THREAD

**Issue by ArunPrasaath** [antonydeepak/ResumeParser#31]
Hi Antony,
Thanks for the parser, it was working great whenever i process resume directly in the powershell. But
when i import the project(Resume Transducer) in eclipse, and tried to run the project am getting the following error at  

> Could not reload creole directory file:/D:/ResumeParser/GATEFiles/plugins/ANNIE/
gate.util.GateException: couldn't open creole.xml
	at gate.creole.CreoleRegisterImpl.registerDirectories(CreoleRegisterImpl.java:299)
	at gate.util.persistence.PersistenceManager.loadObjectFromUrl(PersistenceManager.java:921)
	at gate.util.persistence.PersistenceManager.loadObjectFromFile(PersistenceManager.java:841)
	at code4goal.antony.resumeparser.Annie.initAnnie(Annie.java:38)
	at code4goal.antony.resumeparser.ResumeParserProgram.loadGateAndAnnie(ResumeParserProgram.java:105)
	at code4goal.antony.resumeparser.ResumeParserProgram.main(ResumeParserProgram.java:286)

> 
@ the line of the code in Annie.java `annieController` = (CorpusController) `PersistenceManager.loadObjectFromFile(annieGapp);`
I don't know much about how to resolve this above error, since i don't have much experience in using external JAR like Annie.

**Comment by SebastianCaceres** [comment]
I'm having the same problem, it seems that the root cause has to do something with the ParserException class in the lucene-core. Have you been able to fix it?


`log4j:WARN No appenders could be found for logger (org.apache.pdfbox.pdfparser.PDFObjectStreamParser).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Initialising basic system...
...basic system initialised
Initialising processing engine...
Could not reload creole directory file:/C:/tmp/ResumeSearch/ResumeParser/GATEFiles/plugins/Information_Retrieval/
gate.util.GateException: couldn't open creole.xml
        at gate.creole.CreoleRegisterImpl.registerDirectories(CreoleRegisterImpl.java:299)
        at gate.util.persistence.PersistenceManager.loadObjectFromUrl(PersistenceManager.java:911)
        at gate.util.persistence.PersistenceManager.loadObjectFromFile(PersistenceManager.java:831)
        at code4goal.antony.resumeparser.Annie.initAnnie(Annie.java:40)
        at code4goal.antony.resumeparser.ResumeParserProgram.loadGateAndAnnie(ResumeParserProgram.java:95)
        at code4goal.antony.resumeparser.ResumeParserProgram.main(ResumeParserProgram.java:274)
Caused by: java.lang.NoClassDefFoundError: org/apache/lucene/queryParser/ParseException
        at gate.creole.ir.lucene.LuceneIREngine.<init>(LuceneIREngine.java:44)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at gate.Factory.createResource(Factory.java:285)
        at gate.Factory.createResource(Factory.java:159)
        at gate.creole.CreoleXmlHandler.endElement(CreoleXmlHandler.java:387)
        at org.jdom.output.SAXOutputter.endElement(SAXOutputter.java:1077)
        at org.jdom.output.SAXOutputter.element(SAXOutputter.java:905)
        at org.jdom.output.SAXOutputter.elementContent(SAXOutputter.java:1126)
        at org.jdom.output.SAXOutputter.elementContent(SAXOutputter.java:1098)
        at org.jdom.output.SAXOutputter.element(SAXOutputter.java:897)
        at org.jdom.output.SAXOutputter.output(SAXOutputter.java:621)
        at gate.creole.CreoleRegisterImpl.processFullCreoleXmlTree(CreoleRegisterImpl.java:374)
        at gate.creole.CreoleRegisterImpl.parseDirectory(CreoleRegisterImpl.java:344)
        at gate.creole.CreoleRegisterImpl.registerDirectories(CreoleRegisterImpl.java:291)
        ... 5 more
**Caused by: java.lang.ClassNotFoundException: org.apache.lucene.queryParser.ParseException**
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 23 more`
