### ISSUE TITLE
I'm getting this error when run on Linux. Please help

### ISSUE THREAD

**Issue by martinvml** [antonydeepak/ResumeParser#9]
Exception in thread "main" java.lang.NoClassDefFoundError: gate/SimpleAnnotation
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
	at java.lang.Class.getMethod0(Class.java:2866)
	at java.lang.Class.getMethod(Class.java:1676)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: gate.SimpleAnnotation
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

**Comment by martinvml** [comment]
Please help me to run this application on Ubuntu.

**Comment by tim-peterson** [comment]
I just got the same error. Didn't have it a few days ago. Was something updated?

**Comment by tim-peterson** [comment]
Ubuntu unlike Mac are case sensitive. So `GATEFILES` should be `GATEFiles`.

So you need this:

`java -cp 'bin/*:../GATEFiles/lib/*:../GATEFiles/bin/gate.jar:lib/*' code4goal.antony.resumeparser.ResumeParserProgram <input_file> [output_file]`

instead of this:

`java -cp 'bin/*:../GATEFiles/lib/*:../GATEFILES/bin/gate.jar:lib/*' code4goal.antony.resumeparser.ResumeParserProgram <input_file> [output_file]`

**Comment by antonydeepak** [comment]
I merged the changes. Thanks Tim.
